name: Test Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Package
      run: |
        pip install .
    - name: Load All Modules
      run: |
        for i in `ls zertoapl`; do python -c "import zertoapl.${i%.*}"; done;
